os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/{{cookiecutter.gcloud_project}}/{{cookiecutter.project_slug}}
    - IMAGE_TAG=${TRAVIS_BRANCH}

before_install:
  - make setup

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .

script:
  - make style
  - make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
  - docker-compose exec -e ENVIRONMENT=testing web tox -e py36 -- --cov-report=xml --cov-report=term
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - <GENERATE SECURE TOKEN>
    on_success: change
    on_failure: change
    on_pull_requests: false
