os: linux
language: python
python: "3.7"

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/{{cookiecutter.gcloud_project}}/{{cookiecutter.project_slug}}
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_TIMESTAMP=$(date --utc --iso-8601=seconds)
  - BUILD_DATE=$(date --utc --iso-8601=date)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}

before_install:
- pip install tag-spy
- make setup

install:
- make build

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web tox -e py36 -- --cov-report=xml --cov-report=term
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- make push

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - <GENERATE SECURE TOKEN>
    on_success: change
    on_failure: change
    on_pull_requests: false
