sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  - TARGET=test-travis
  - TARGET=flake8
  - TARGET=isort
  - TARGET=license

matrix:
  fast_finish: true

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      before_script:
        - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
      script:
        - make build
        - docker images
        - docker push ${DOCKER_USERNAME}/tag
    - stage: test
      before_script:
        - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
      script:
        - docker pull ${DOCKER_USERNAME}/tag
        - make ${TARGET}
    - stage: deploy
      before_script:
        - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
      script:
        - docker pull ${DOCKER_USERNAME}/tag
      deploy:
        provider: script
        script: ./scripts/push_to_hub.sh
        on:
          branch: master

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
