sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO={{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

before_install:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin

install:
  - docker build -t ${IMAGE} .
  - make setup

script:
  - make flake8
  - make isort
  - make license
  - make pipenv-check
  - make test-travis

deploy:
  provider: script
  script: ./scripts/push_to_hub.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
