sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_TAG=travis-ci
  matrix:
    - TARGET=test-travis
    - TARGET=flake8
    - TARGET=isort
    - TARGET=license

matrix:
  fast_finish: true

before_script:
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
  - make network

script:
  - docker pull {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${IMAGE_TAG}
  - make ${TARGET}

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - make build
        - docker push {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${IMAGE_TAG}
    - stage: deploy
      script:
        - docker pull {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${IMAGE_TAG}
      deploy:
        provider: script
        script:
         - docker tag {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${IMAGE_TAG} {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${TRAVIS_COMMIT::12}
         - docker tag {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${IMAGE_TAG} {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${TRAVIS_BRANCH}
         - docker push {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${TRAVIS_COMMIT::12}
         - docker push {{cookiecutter.docker_organization}}/{{cookiecutter.project_slug}}:${TRAVIS_BRANCH}

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
