sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  - TARGET=test-cov
  - TARGET=flake8
  - TARGET=isort
  - TARGET=license

matrix:
  fast_finish: true

install:
  - make build

script:
  - make ${TARGET}

before_deploy:
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}

deploy:
  provider: script
  script: ./scripts/push_to_hub.sh
  on:
    all_branches: true
    condition: ${TARGET} = "test-cov"

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
