version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}
      - SENTRY_DSN=${SENTRY_DSN}
    command: gunicorn -c gunicorn.py {{cookiecutter.project_slug}}.wsgi:app
