version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: {{cookiecutter.github_username}}/{{cookiecutter.project_slug}}:${IMAGE_TAG:-latest}
    networks:
      - {{cookiecutter.github_username}}
      - default
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:*}
      - SENTRY_DSN=${SENTRY_DSN}
    command: gunicorn -c gunicorn.py {{cookiecutter.project_module}}.wsgi:app

networks:
  {{cookiecutter.github_username}}:
    external: true
