version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src/:/app/src/"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost}
      - SENTRY_DSN=${SENTRY_DSN}
    command: gunicorn -c configuration.py {{cookiecutter.project_slug}}.wsgi:app
