version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_TAG=${BASE_TAG:-alpine}
        - BUILD_COMMIT=${BUILD_COMMIT:-unknown}
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-unknown}
    image: gcr.io/{{cookiecutter.gcloud_project}}/{{cookiecutter.project_slug}}:${IMAGE_TAG:-latest}
    user: giraffe
    networks:
      default:
      {{cookiecutter.github_username}}:
        aliases:
          - {{cookiecutter.project_slug}}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/{{cookiecutter.project_module}}/wsgi.py
      - SCRIPT_NAME=${SCRIPT_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}

# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  {{cookiecutter.github_username}}:
    external: true
