version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
    command: gunicorn -c gunicorn.py {{cookiecutter.project_slug}}.wsgi:app
