language: python
python: "3.6"
git:
  depth: 2
branches:
  - master
before_install:
  - pip install -U pip setuptools wheel
  - pip install pipenv
install:
  - pipenv install --dev --system
script: pytest
notifications:
  on_success: never
  on_failure: always
