language: python
python: "3.6"
git:
  depth: 2
branches:
  - master
  - devel
before_install:
  - pip install -U pip setuptools wheel
install:
  - pip install cookiecutter flake8 pytest pytest-cookies
script: pytest
notifications:
  on_success: never
  on_failure: always
